version: "3.8"


services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  chat-bot:
    image: hisptanzania/chat-bot:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
